ci:
  collect:
    numberOfRuns: 3
    url:
       - http://localhost:4000
  assert:
    preset: lighthouse:recommended
    assertions:
      offscreen-images: 'off'
      valid-source-maps: 'off'
      robots-txt: 'off'
      uses-webp-images: 'off'
      uses-optimized-images: 'warn'
      color-contrast: 'off'
      button-name: 'warn'
      csp-xss: 'off'
      errors-in-console: 'warn'
      font-display: 'warn'
      image-alt: 'warn'
      image-size-responsive: 'warn'
      maskable-icon: 'warn'
      meta-description: 'warn'
      non-composited-animations: 'warn'
      service-worker: 'warn'
      tap-targets: 'warn'
      themed-omnibox: 'warn'
      unsized-images: 'warn'
      unused-css-rules: 'warn'
      unused-javascript: 'warn'
      first-contentful-paint:
        - error
        - maxNumericValue: 2750
          aggregationMethod: optimistic
      interactive:
        - error
        - maxNumericValue: 20000
          aggregationMethod: optimistic
      total-byte-weight:
        - error
        - minScore: 0.5
          aggregationMethod: optimistic
      unminified-javascript:
        - error
        - maxLength: 1
          aggregationMethod: optimistic
      uses-text-compression:
        - error
        - maxLength: 13
          aggregationMethod: optimistic
      uses-rel-preconnect:
        - error
        - maxLength: 5
          aggregationMethod: optimistic
      linkName:
        - error
        - minScore: 0
          aggregationMethod: optimistic

  upload:
    target: 'temporary-public-storage'
