ci:
  collect:
    numberOfRuns: 3
    url:
       - http://localhost:4000
       - http://localhost:4000/electronics-spa/en/USD/Brands/Canon/c/brand_10
       - http://localhost:4000/electronics-spa/en/USD/product/832386/ef-300mm-f-2.8l-is-usm
    startServerCommand: 'yarn serve:ssr'
  assert:
    preset: lighthouse:recommended
    assertions:
      bootup-time:
        - error
        - minScore: 0.44
      button-name: 'warn'
      color-contrast: 'warn'
      csp-xss: 'warn'
      cumulative-layout-shift:
        - error
        - minScore: 0.03 
        # - minScore: 0.02 
      errors-in-console: 'warn'
      first-contentful-paint:
        - error
        - minScore: 0.3
      first-meaningful-paint: 'warn'
      font-display: 'warn'
      image-alt: 'warn'
      image-size-responsive: 'warn'
      interactive:
        - error
        - minScore: 0.04
      largest-contentful-paint: 'warn'
      legacy-javascript: 'warn'
      link-name: 'warn'
      mainthread-work-breakdown:
        - error
        - minScore: 0.14
      maskable-icon: 'warn'
      max-potential-fid: 'warn'
      meta-description: 'warn'
      modern-image-formats: 'warn'
      non-composited-animations: 'warn'
      offscreen-images: 'warn'
      render-blocking-resources:
        - error
        - maxLength: 2
      robots-txt: 'warn'
      server-response-time: 'warn'
      service-worker: 'warn'
      speed-index:
        - error
        - minScore: 0.1
      tap-targets: 'warn'
      themed-omnibox: 'warn'
      total-byte-weight:
        - error
        - minScore: 0.65
      unminified-javascript: 'warn'
      unsized-images: 'warn'
      unused-css-rules:
        - error
        - maxLength: 6
        - minScore: 0.19
        # - minScore: 0.19
        # - minScore: 0.14
        # - minScore: 0.21
      unused-javascript: 'warn'
      uses-optimized-images: 'warn'
      uses-rel-preconnect: 'warn'
      uses-webp-images: 'warn'
      valid-source-maps: 'warn'
      uses-text-compression: 'warn'
  upload:
    target: 'temporary-public-storage'
