dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^epic\\/.*$/"
    - "/^release\\/.*$/"
defaults: &defaults
  script: "./ci-scripts/e2e-cypress.sh -s regression"
jobs:
  - script: "./build.sh sonar"
  - script:
    name: "Cypress regression tests, 1st job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
  - script:
    name: "Cypress regression tests, 2st job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
  - script:
    name: "Cypress regression tests, 3rd job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
  - script:
    name: "Cypress regression tests, 4th job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
addons:
  chrome: stable
  sonarcloud:
    organization: sap
