dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
jobs:
  - script: "./ci-scripts/deploy-hs.sh"
addons:
  chrome: stable
  sonarcloud:
    organization: sap
