dist: trusty
language: node_js
node_js:
  - 10.14.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - master
    - "/^feature\\/.*$/"
    - "/^hotfix\\/.*$/"
    - "/^release\\/.*$/"
script: ./build.sh sonar
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/storefrontapp
  on:
    branch: develop
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  chrome: stable
  sonarcloud:
    organization: sap
