dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^epic\\/.*$/"
    - "/^release\\/.*$/"
    - "/^integration-libs\\/.*$/"
defaults: &defaults
  script: "export CYPRESS_CONFIG=cypress.ci.json && export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
jobs:
  - script:
    name: "E2E tests for B2C, 1st job"
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 2nd job"
    <<: *defaults
addons:
  chrome: stable
