dist: trusty
language: node_js
node_js:
  - 10.14.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - master
    - "/^feature\\/.*$/"
    - "/^hotfix\\/.*$/"
    - "/^release\\/.*$/"
script: ./build.sh sonar
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  chrome: stable
  sonarcloud:
    organization: sap
