dist: bionic
language: node_js
node_js:
  - 12.16.1
before_install:
  - npm install -g @lhci/cli@0.8.x
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^epic\\/.*$/"
    - "/^release\\/.*$/"
defaults: &defaults
  script: "export CYPRESS_CONFIG=cypress.ci.json && export SPA_ENV='ci,b2c' && ./ci-scripts/e2e-cypress.sh"
jobs:
  - script:
    name: "Lighthouse CI"
    - yarn build:libs && yarn build && yarn build:ssr:ci
    - lhci autorun
addons:
  chrome: stable
  sonarcloud:
    organization: sap
