language: node_js
node_js:
- 8.9.0
dist: trusty
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
jobs:
  include:
    - stage: "Spartacus build"
      name: "Unit tests"
      script: "./ci-scripts/unit-tests.sh"
      name: "End to end tests"
      script: "./ci-scripts/e2e-tests.sh"
      name: "Validation"
      script: "./ci-scripts/validate.sh"
      name: "Lint"
      script: "./ci-scripts/lint.sh"
      name: "SonarCloud scanner"
      script: sonar-scanner
notifications:
  slack:
    secure: Qz4eaqZJ+4XeEDpl818ZwlXKs1jbY9prg+0+DNQ5cVO7f2nDGI1PTMSsLVihRss39Wx/NW+f6UJGaJLMESzvFlKtPqKePbdA+U+EaxVFh/qIAC2Q1oVA1hfrMVtYjB6h0FNZYMoGjOQHHELb9ojJeHrl4CiMU6BJgoJ6rEhSFyJhuua2RwFAxnKWyxXkhf42SUpJKWyw8cWrW9dHvnHXA0je8cthzj7xLFsiPtJmH8cH8MkVrDh2kPZ1j1pMMia+20zk2ezQhMdN/SBeXN8WPn8dVtEoNVpxrZYiWhJfHpAx4uw3VFgqIdOyCTrgwhwnN9Njx1j7pHRt+amsnLHHZUR/QgJKocGSchkYp7FpixTIrvblCU0XJBKv1bYfJ9jOipCDG3FTMLAp/Vqfuir1ilKmR2upaUxigX3/TK7dn4U97aECrPGnl1AbQijfFlXl/sDvYNrbGU02FIN8a1VPEgq4J9V27dhZ4O5AWjn6EyK3hOgk8EwxKzi0gwWmXUBwZIkS6efZbEgXcggaiRf5jw+2gVBocrFhik4CmdpXmWmenjg5Uo9Cw/t/x7CGHxiWtDErfgQvU5Sai18WrU/yjqTYptCaQiz1Mvyn3viE6mhhFap4xIRnvJBG1nnGPiXnb02lYfS5CFAopf54GkhyYPzKnP5XYHJStZpbjanrIQI=
  email:
    on_failure: change
    on_success: change
addons:
  chrome: stable
  sonarcloud:
    organization: sap
    token:
      secure: I2+ah2XiEbJ6MwWG51B0Vqpsv7KhnqMJzhoPTun6iPxlMXVqIJm1bCRkutOtlVJ+65UDj20H6ld0Tc9LOEz3Uvjk/ZSmHIA/7esC1kRcOu62VE8k/Y+nH8epI3dBr70Yymn9V27kqBNTMs+i2qC8z/+2cd0DBrAPtRQXcPedd4kw41kdeFBzmI/ng1uOhadLF2U63s+krkfLSoaBcCkksll3KsnDe/ItJN1Hu7oZ5UQUxcbP8LHDHBIm3YuMDh9WLWvp9zypglS5as8GC55Zi8dDFlqXrcVcKa5niN8Q/UOByBDy1JiM6kJbc/mjbpjdQMAoCz9YjkPhd181hbz0rocxqPmbEszwPVNadRbz3mUjTz/us+3ekrw3/i4DhuzmGlV2kRkbXIquegecivNnWMP8JyZDRerR8onSKS+YMmEI1t7tOLWHCJ4ImkfMWGVbT8t27ZWO2bhDu+N0JxyPuMRSVPRXvhEAqIbts8OdeITxQiWcSdI2Q/Fsfsft7uUBJhhU8S+c6Gs0LuCikG4WfchjCUxK5kFQqEAqLX+BUJbQxw6J2S+geoAzxWhQrs+O/GzXDzuez8Z3Ou8hk2w/l+VSJ2MuiJq/jlcSmVkYUUtKhvPfq/fcLtp9Lt9dUCw/8Es9jbvtg/0i2iyajkF/9PRc6UzhcYu/sk8xopNK4bQ=
