# https://docs.saucelabs.com/web-apps/automated-testing/cypress/
# https://docs.saucelabs.com/web-apps/automated-testing/cypress/yaml/
#apiVersion: v1alpha
apiVersion: v1
kind: cypress
sauce:
  region: eu-central-1 #us-west-1 #headless-us-east #eu-central-1 # or us-west-1
  concurrency: 12
  metadata:
    tags:
      - cypress
      - default
    build: "config-ex6-b2c-all $CURRENT_TIME"
  tunnel:
    name: "name"
cypress:
  version: 10.7.0
  configFile: "cypress.config.ts" # We determine related files based on the location of the config file.
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  - name: "Cypress Chrome Mac - Homepage "
  # - name: "Cypress Chrome W11"
    #platformName: "Windows 11"
    #screenResolution: "1400x1050"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    config:
      #testFiles: ["cypress/e2e/regression/homepage/homepage.core-e2e.cy.ts"]
      specPattern: ["cypress/e2e/regression/homepage/*.*"]
  - name: "Cypress Chrome Mac - anonymous consents "
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/anonymous-consents/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - ASM "
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/asm/*.core-e2e.cy.ts"]      
  - name: "Cypress Chrome Mac - Cart"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/cart/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Checkout "
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/checkout/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Consignment Tracking"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/consignment-tracking/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Coupons"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/coupons/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Image Zoom"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/image-zoom/*.core-e2e.cy.ts"]  
  - name: "Cypress Chrome Mac - Inventory Display"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/inventory-display/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Miscellaneous"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/miscellaneous/*.core-e2e.cy.ts"]                      
  - name: "Cypress Chrome Mac - My Account"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/my-account/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - notification"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/notification/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Orders"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/orders/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Password Visibility"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/password-visibility/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Product Configurator"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/product_configurator/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Product Details"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/product_details/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Product Carousel"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/product-carousel/*.core-e2e.cy.ts"]                                    
  - name: "Cypress Chrome Mac - Product Search"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/product-search/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Promotions"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/promotions/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Qualtrics"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/qualtrics/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Redirects"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/redirects/*.core-e2e.cy.ts"]  
  - name: "Cypress Chrome Mac - Reset Password"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/reset-password/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Save for later"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/save-for-later/*.core-e2e.cy.ts"] 
  - name: "Cypress Chrome Mac - Scrolling"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/scrolling/*.core-e2e.cy.ts"]   
  - name: "Cypress Chrome Mac - Site Context"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/site-context/currency/*.core-e2e.cy.ts"]  
      specPattern: ["cypress/e2e/regression/site-context/language/*.core-e2e.cy.ts"]  
  - name: "Cypress Chrome Mac - Storefinder"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/storefinder/*.core-e2e.cy.ts"]                                       
  - name: "Cypress Chrome Mac - User Access"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/user_access/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - variants"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/variants/*.core-e2e.cy.ts"]
  - name: "Cypress Chrome Mac - Wishlist"
    browser: "chrome"
    platformName: "macOS 12"
    screenResolution: "1600x1200"
    headless: true
    #shard: "concurrency"
    config:
      specPattern: ["cypress/e2e/regression/wishlist/*.core-e2e.cy.ts"]                         

npm:
  dependencies:
    - "@cypress/webpack-preprocessor"
    - "webpack"
    - "@angular/animations"
    - "@angular/common"
    - "@angular/compiler"
    - "@angular/core"
    - "@angular/forms"
    - "@angular/platform-browser"
    - "@angular/platform-browser-dynamic"
    - "@angular/platform-server"
    - "@angular/pwa"
    - "@angular/router"
    - "@angular/service-worker"
    - "@ng-bootstrap/ng-bootstrap"
    - "@ng-select/ng-select"
    - "@ngrx/effects"
    - "@ngrx/router-store"
    - "@ngrx/store"
    - "@nguniversal/express-engine"
    - "@types/googlemaps"
    - "angular-oauth2-oidc"
    - "bootstrap"
    - "comment-json"
    - "express"
    - "hamburgers"
    - "i18next"
    - "i18next-http-backend"
    - "ngx-infinite-scroll"
    - "parse5"
    - "rxjs"
    - "ts-loader"
    - "tslib"
    - "zone.js"
    - "typescript"
    - "@testing-library/cypress"
    - "cypress-file-upload"
