on:
  push:
    branches:
      - develop
      - 'epic/**'
      - 'release/**'
      - simulate-develop-123
name: Cache libs (dist)
jobs:
  cacheBuildedLibs:
    name: Builded libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cache builded libs
        uses: ./.github/cache-builded-libs
