on:
  pull_request:
    types: [ready_for_review]
    branches:
      - develop
      - develop-*
      - release-*
  workflow_dispatch:
    # empty as it is used only to manually trigger the workflow
  
env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
  GH_TOKEN: ${{ github.token }}
  NODE_VERSION: '20'
  AMP_API_TOKEN: ${{ secrets.AMP_API_TOKEN }}
  CONTINUUM_REGISTRY_TOKEN: ${{ secrets.CONTINUUM_REGISTRY_TOKEN }}

concurrency: 
  group: ci-merge-checks-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Merge Checks
jobs:
  no_retries: 
    name: MC - Prevent retries
    # E2Es can't be retried.  Moreover, in some retry cases, they don't run
    # and the job returns a success code.
    runs-on: ubuntu-latest
    steps:
      - name: Forcefully fail build if jobs are all retried
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Please push a commit to trigger the build. To push an empty commit you can use `git commit --allow-empty -m "Trigger Build"`') 
        if: ${{ github.run_attempt > 1 }}
  
  merge_checks_result:
    needs: []
    name: MC - Result
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Aggregate Required Job Results
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `# Merge Checks Failed
                Please push a commit to re-trigger the build. 
                To push an empty commit you can use \`git commit --allow-empty -m "Trigger Build"\``
            })
            core.setFailed('Please push a commit to re-trigger the build. To push an empty commit you can use `git commit --allow-empty -m "Trigger Build"`')
        if: |
          needs.b2c_e2e_tests.result == 'failure' || needs.b2c_e2e_tests.result == 'cancelled' ||
          needs.b2c_ssr_e2e_tests.result == 'failure' || needs.b2c_ssr_e2e_tests.result == 'cancelled' || 
          needs.b2b_e2e_tests.result == 'failure' || needs.b2b_e2e_tests.result == 'cancelled'
