on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize]
env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
  NODE_VERSION: '16'

concurrency: 
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Spartacus build pipeline
jobs:
  no_retries: 
    name: Verify re-run of all jobs
    runs-on: ubuntu-latest
    steps:
      - name: Forcefully fail build if jobs are all retried
        run: | 
          echo ${{ github.event.pull_request.head.sha }} 1
          echo ${{ github.sha }} 2
