on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Config check
jobs:
  configCheck:
    name: Dependencies and tsconfig files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Yarn
        run: yarn
      - name: Check configurations
        run: yarn config:check
