on:
  pull_request:
    types: [opened, synchronize, reopened]
name: Hosting service
jobs:
  hostingServiceDeploy:
    name: Deployment bot
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deployment bot
        uses: ./github/deploy-hs
        env:
          GHT_USER: ${{ secrets.GHT_USER}}
          GHT_TOKEN: ${{ secrets.GHT_TOKEN}}
          UPP_TENANT: ${{ secrets.UPP_TENANT}}
          UPP_CLIENT: ${{ secrets.UPP_CLIENT}}
          UPP_SECRET: ${{ secrets.UPP_SECRET}}
      