on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  e2eTests:
    name: Flaky e2e tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome83-ff77
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Install cypress dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: projects/storefrontapp-e2e-cypress
      - name: Build Spartacus
        run: yarn build:libs
      - name: Run e2es
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
        run: yarn e2e:cy:start-run-flaky-ci:2005
