on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  e2eTests:
    name: Flaky e2e tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome83-ff77
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install root dependencies
        uses: bahmutov/npm-install@v1
      - name: Install cypress dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: projects/storefrontapp-e2e-cypress
      - name: Build Spartacus
        run: yarn build:libs && yarn build:ci:2005
      - name: Install pm2 server
        run: npm install -g pm2
      - name: Start server
        run: pm2 start --name "spartacus" serve -- dist/storefrontapp --single -p 4200
      - name: Run e2es
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
        run: yarn e2e:cy:run:ci:flaky:2005
